### ISSUE TITLE
Upgrade Gradle version for JDK11

### ISSUE THREAD

**Issue by Mrc0113** [SolaceSamples/solace-samples-mqtt#44]
Opening this issue due to developer feedback of: gradle version needs update to 4.10.2, otherwise it won't run with JDK11. 

Note: Consider going to latest gradle assuming it is backwards compatible with Java 8 when working this bug.

**Comment by aaron-613** [comment]
Opened PR: https://github.com/SolaceSamples/solace-samples-mqtt/pull/46

Built and tested samples using JDK 8 and JDK 17.

**Comment by aaron-613** [comment]
Done and closed!  @Mrc0113 can you tell whomever developer you mentioned in the original post that this has been fixed..?  Although that was 2 years ago!
