### ISSUE TITLE
Clearer exception messages in MQTT samples

### ISSUE THREAD

**Issue by ngdavid1013** [SolaceSamples/solace-samples-mqtt#45]
I have a customer ticket where they complained that the MQTT exception message is not very clear.
e.g. This is their sample output:
              reason 5
              msg Not authorized to connect
              loc Not authorized to connect
              cause null
              excep Not authorized to connect (5)
              Not authorized to connect (5)
                      at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28)
                      at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:990)
                      at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:118)
                      at java.lang.Thread.run(Thread.java:748)

If I may suggest to have a few more characters and put the exception first;
e.g.
Exception: Not authorized to connect (5)
Reason code: 5
Reason message: Not authorized to connect
Localized message: Not authorized to connect
Cause: null.

**Comment by ngdavid1013** [comment]
Associated RT42042

**Comment by Mrc0113** [comment]
Hi @ngdavid1013, 

The exception you posted seems to be generated by the Paho client library and not by our samples. Is that correct or can you point to which sample is creating the unclear exception?

**Comment by ngdavid1013** [comment]
Hi Marc,

Apologize for such a late reply.
I am afraid it is from our code base in https://github.com/SolaceSamples/solace-samples-mqtt/tree/master/src/main/java/com/solace/samples

In all of the samples in that above directory, whenever there is an MqttException, we will display those error messages.

Thanks,
David.

**Comment by aaron-613** [comment]
Hi @ngdavid1013 , your requested changes have now been implemented:

```
       } catch (MqttException me) {
            System.out.println("Exception:   " + me);
            System.out.println("Reason Code: " + me.getReasonCode());
            System.out.println("Message:     " + me.getMessage());
            if (me.getCause() != null) System.out.println("Cause:       " + me.getCause());
            me.printStackTrace();
        }
```

And a couple other small changes.  Thanks!
