### ISSUE TITLE
Improve Solace message router properties overview in tutorials

### ISSUE THREAD

**Issue by mdspielman** [SolaceSamples/solace-samples-mqtt#8]
The tutorials have a summary of the required "Solace message router properties" like this: https://github.com/SolaceSamples/solace-samples-mqtt/blob/master/docs/_tutorials/publish-subscribe.md

This is very Solace generic and should be updated to discuss the MQTT resources as well as the Solace resources. For example the message-vpn is implied by port choices and the MQTT session clientId will drive the session name on the message router. So suggestion from the field is to add a new column which is called "MQTT Resource" and map this to the Solace resource as well (i.e. rename "Resource" column to "Solace Resource".

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️
