### ISSUE TITLE
Need to take advantage of Paho 1.1.0 Reconnect logic

### ISSUE THREAD

**Issue by KenBarr** [SolaceSamples/solace-samples-mqtt#9]
For MQTT Java 1.1.0 Paho API, all the publish buffered while offline and auto-reconnect logic has been ported from the Android API to MQTT.  These features work niceley with Solace HA and DR as described here:
https://github.com/KenBarr/mqtt3.1.1_1.1.0_test

Our sample should not just exit on disconnect but actually exemplify the resiliency of Solace + MQTT by going through the reconnect logic path.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️
